import Head from 'next/head';
import Main from '../../components/Main';
import About from '../../components/About';
import Skills from '../../components/Skills';
import Projects from '../../components/Projects';
import Contact from '../../components/Contact';


function Home() {
  
  return (
    <div>
      <Head>
        <title>Florine Portfolio</title>
        <meta property="description" content="Generated by create next app" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  )
}

export default Home;